config/routes.rb
RubyKb::Application.routes.draw do

  devise_for :users

  get "home/index"

  resources :users

  resources :articles

  resources :topics

  resources :topics do
    member do
      get 'query'
    end
  end

  resources :articles do
    collection do
      post 'search'
    end
  end
  
  resources :topics, only: [:show, :edit] do
    resources :articles
  end

  resources :articles,  only: [:show] do
    resources :feedbacks
  end

  root :to => 'home#index'

end

app/views/layouts/shared/_footer.html.erb
<footer id="footer">
  <p class="pull-right"><a href="#middle">Back to top</a></p>
  <p>
    Ruby on Rails for Starters Workshop, &copy; 2013.
  </p>        

  Based on <a href="http://twitter.github.com/bootstrap/">Bootstrap</a>. 
  Hosted on <a href="http://pages.github.com/">GitHub</a>. <br>
  Made by <b>Yuan Sheng Liu (Lewis)</b>. Contact him <a href="mailto:lex.liu@hotmail.com">lex.liu@hotmail.com</a>
 

</footer>

app/views/layouts/shared/_header_bar.html.erb
<div class="navbar navbar-fixed-top">
	<div class="navbar-inner">
		<div class="container">
			<a class="brand" href="/">Ruby on Rails for Starters</a>

			<div class="nav-collapse collapse" id="main-menu">
				<ul class="nav">
					<li>
						<%= link_to "Home", root_path %>
					</li>
				
					<li>
						<%= link_to "Post an Article", new_article_path %>
					</li>					
					<li style="padding: 7px 0px 0px 10px;">
		<%= form_tag(search_articles_path, :remote=>true,  :html=>{:class=>"navbar-search"}) do %>
					<input type="text" class="search-query span2" name="search" placeHolder="Search">
					<button type="submit" class="btn btn-small">Search</button>	
		<% end %>
					</li>
				</ul>


				<ul class="nav pull-right">
					<% if user_signed_in? %>
						<% if is_admin_user? %>
							<li class="dropdown" id="admin-menu">
				            <a class="dropdown-toggle" data-toggle="dropdown" href="#">Admin<b class="caret"></b></a>
				            <ul class="dropdown-menu">
				              <li>
				              	<%= link_to "Accounts", users_path %>
				              </li>
				              <li>
				              	<%= link_to "Topics", topics_path %>
				              </li>
				            </ul>
				          	</li>		
			          	<% end %>

						<li class="disabled">
							<a>Welcome <%= current_user.name %></a>
						</li>
						<li>
							<%= link_to "Sign out", destroy_user_session_path, method: :delete %>
						</li>						
					<% else %>
						<li> 
							<%= link_to "Sign in", new_user_session_path %>
						</li>
						<li> 
							<%= link_to "Sign up", new_user_registration_path %>
						</li>
					<% end %>
				</ul>
			</div>
		</div>
	</div>
</div>

    <script type="text/javascript">
        $(document).ready(function () {
            $('.dropdown-toggle').dropdown();
        });
   </script>

app/views/layouts/shared/_left_panel_topic.html.erb
<div class="span3">
	<h3>Topics</h3>	
	<div class="well" style="padding: 4px 0;">
    	<ul class="nav nav-list" id="listTopic">
			<% @topics.each do |topic| %>
				<% if selectTopicId == topic.id %>
				<li id="lt<%= topic.id %>" class="active"><%= link_to topic.name, query_topic_path(topic), remote: true %></li>
				<% else %>
				<li id="lt<%= topic.id %>"><%= link_to topic.name, query_topic_path(topic), remote: true %></li>
				<% end %>
			<% end %>
		</ul>      	
  	</div>
</div>