config/routes.rb
RubyKb::Application.routes.draw do

  devise_for :users

  get "home/index"

  resources :users

  resources :articles

  resources :topics

  resources :topics do
    member do
      get 'query'
    end
  end

  resources :articles do
    collection do
      post 'search'
    end
  end
  
  resources :topics, only: [:show, :edit] do
    resources :articles
  end

  resources :articles,  only: [:show] do
    resources :feedbacks
  end

  root :to => 'home#index'

end

app/models/article.rb
class Article < ActiveRecord::Base
  attr_accessible :content, :title, :topic_id, :user_id

  validates :title, presence:true, uniqueness:true
  validates :content, presence:true

  belongs_to :topic

  belongs_to :user

  has_many :feedbacks

  has_many :votes
  
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  # GET /articles
  # GET /articles.json
  before_filter :authenticate_user!, except: [:show, :index, :search]
  before_filter :find_article, only: [:show, :edit, :update, :destroy]

  def index
    @articles = Article.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @articles }
    end
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
    @article = Article.find(params[:id])

    @topics = Topic.all()

    @feedback = Feedback.new
    
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @article }
    end
  end

  # GET /articles/new
  # GET /articles/new.json
  def new
    @article = Article.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @article }
    end
  end

  # GET /articles/1/edit
  def edit
    @article = Article.find(params[:id])
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(params[:article])

    @article.user = current_user


    respond_to do |format|
      if @article.save

        #QuestionsMailer.comment_notfication(current_user, @article).deliver
        QuestionsMailer.delay.comment_notfication(current_user, @article)

        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render json: @article, status: :created, location: @article }
      else
        format.html { render action: "new" }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # POST /articles/search
  def search
    if (params[:search].length>0)
      searchParam = "%" + params[:search] + "%"
      @exception = ""
      begin
        @articles = Article.where("title like ? or content like ?", searchParam, searchParam)
      rescue StandardError=>e
        @exception = e
      end

      respond_to do |format|
        format.js
      end
    end
  end

  # PUT /articles/1
  # PUT /articles/1.json
  def update
    @article = Article.find(params[:id])

    respond_to do |format|
      if @article.update_attributes(params[:article])
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article = Article.find(params[:id])
    @article.destroy

    respond_to do |format|
      format.html { redirect_to articles_url }
      format.json { head :no_content }
    end
  end

  private

  def find_article
    @article = Article.find(params[:article_id] || params[:id])
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_article.html.erb
<table id="articles" class="table table-bordered table-striped table-hover">
    <thead>
        <tr>
            <th>Publish Date</th>
            <th>Title</th>
            <th>Brief</th>
        </tr>
    </thead>
    <tbody>
        <% searchArticles.each do |article| %>
            <tr>
                <td><%= formatted_date_time(article.created_at) %></td>
                <td><%= link_to article.title, article_path(article) %></td>
                <td><%= sanitize(article.content, :tags=>[])[0..50] %></td>
            </tr>
        <% end %>        

    </tbody>
</table>

<script type="text/javascript">
$('#articles').dataTable({
  "sDom": "<'row'<'span6'l><'span6'f>r>t<'row'<'span5'i><'span4'p>>",
  "sPaginationType": "bootstrap",
        "bPaginate": true,
        "bLengthChange": false,
        "bFilter": false,
        "bAutoWidth": true,
        "oLanguage": {
            "sZeroRecords": "No Article Found",
            "sInfo": "Showing _START_ to _END_ of _TOTAL_ articles",
            "sInfoEmpty": "",
        },
    "aaSorting": [[ 0, "desc" ]]
        
}); 
</script>

app/views/articles/_form.html.erb
<script type="text/javascript">
       bkLib.onDomLoaded(function() { nicEditors.allTextAreas() });
</script>

<%= form_for(@article, :html=>{:class=>"form-horizontal well"}) do |f| %>
  <fieldset>    
    <div class="control-group info">
      <label class="control-label" for="selectError">Select a Topic</label>
      <div class="controls">
        <%= select_tag "article[topic_id]", options_for_select(Topic.all.collect{|t| [t.name, t.id]}, @article.topic_id) %>
        <span class="help-inline">Woohoo!</span>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :title, :class=>"control-label", :for=>"title" %>
      <div class="controls">
        <%= f.text_field :title, :id=>"title", :class=>"input-xlarge" %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label "Content (HTML allowed)", :class=>"control-label", :for=>"article_content" %>
      <div class="controls">
        <%= f.text_area :content, :style=>"width: 80%;", :rows=>"15" %>      
      </div>
    </div>

    <div class="form-actions">
      <%= f.submit "Post Article", :class=>"btn btn-primary" %>
      <button type="reset" class="btn">Cancel</button>
    </div>

  </fieldset>  
<% end %>

app/views/articles/_search.html.erb
<h3>Search Result for "<%= params[:search] %>"</h3>	

<%= render :partial => "/articles/article", :locals => {:searchArticles => @articles} %>

app/views/articles/edit.html.erb
<h1>Editing article</h1>

<%= render 'form' %>

<%= link_to 'Show', @article %> |
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<h1>Listing articles</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Content</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @articles.each do |article| %>
  <tr>
    <td><%= article.title %></td>
    <td><%= article.content %></td>
    <td><%= link_to 'Show', article %></td>
    <td><%= link_to 'Edit', edit_article_path(article) %></td>
    <td><%= link_to 'Destroy', article, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Article', new_article_path %>

app/views/articles/new.html.erb
<legend>Post a New Article 
	<small>by: <%= current_user.email %></small>
</legend> 

<%= render 'form' %>

app/views/articles/search.js.erb
<% if @exception.empty? %>
  $("#content").html("<%= j(render :partial => '/articles/search', :object => @articles) %>");

	$('.datatable').dataTable({
	  "sDom": "<'row'<'span6'l><'span6'f>r>t<'row'<'span6'i><'span6'p>>",
	  "sPaginationType": "bootstrap"
	});
  
<% else %>
  alert("there was errors with your search.");
<% end %>

app/views/articles/show.html.erb
<div class="row">

	<%= render :partial => "/layouts/shared/left_panel_topic", :object => @topics,:locals => {:selectTopicId => @article.topic_id} %>

	<div class="span9" id="content">

	  <h1><%= @article.title %></h1>

		<p> Last Updated: <%= formatted_date(@article.created_at) %> 
			<% if current_user = @article.user %>
				<span class="pull-right"><%= link_to 'Edit', edit_article_path(@article) %> </span>
			<% end %>
		</p>
		<p> By: <b><%= current_user.name %></b> </p>

		<p>
		  <%= @article.content.html_safe %>
		</p>

		<h3>Feedbacks</h3>
		<div id="feedbacks" class="well">
			<% @article.feedbacks.each do |feedback| %>
				<div class="control-group"  style="padding: 5px 5px 5px 5px;">
				<div><%= formatted_date(feedback.created_at) %> </div>
				<div><%= feedback.notes %></div>
				</div>
			<% end %>
		</div>
		<%= form_for @feedback, :html=>{:class=>"form-horizontal well"}, remote: true, url: article_feedbacks_path(@article) do |f| %>
		  	<fieldset>    
		  		<h4>Reply to This Article</h4>
			    <div>
			    	<%= f.text_area :notes, :style=>"width: 80%;", :rows=>"5" %>      
			    </div>

			    <p>
			      <%= f.submit "Send Feedback", :class=>"btn" %>
			    </p>

  			</fieldset>  			
		<% end %>

	</div>
</div>