config/routes.rb
RubyKb::Application.routes.draw do

  devise_for :users

  get "home/index"

  resources :users

  resources :articles

  resources :topics

  resources :topics do
    member do
      get 'query'
    end
  end

  resources :articles do
    collection do
      post 'search'
    end
  end
  
  resources :topics, only: [:show, :edit] do
    resources :articles
  end

  resources :articles,  only: [:show] do
    resources :feedbacks
  end

  root :to => 'home#index'

end

app/models/topic.rb
class Topic < ActiveRecord::Base
  attr_accessible :description, :name

  validates :name, presence:true, uniqueness:true
  validates :description, presence:true

  has_many :articles

end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_filter :authenticate_user!, except: [:show, :index, :query]
  before_filter :find_topic, only: [:show, :edit, :update, :destroy]

  # GET /topics
  # GET /topics.json
  def index
    @topics = Topic.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @topics }
    end
  end

  # GET /topics/1
  # GET /topics/1.json
  def show
    @topic = Topic.find(params[:id])

    @topics = Topic.all()
    
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @topic }
    end
  end


  # GET /topics/new
  # GET /topics/new.json
  def new
    @topic = Topic.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @topic }
    end
  end

  # GET /topics/1/edit
  def edit
    @topic = Topic.find(params[:id])
  end

  # GET /topics/1/query
  def query
     @topic = Topic.find(params[:id])   
    
    @articles = Article.where("topic_id = ?", @topic.id )
    @topic.articles = @articles

    respond_to do |format|
      #format.html # show.html.erb
      #format.json { render json: @topic }
      format.js
    end
  end

  # POST /topics
  # POST /topics.json
  def create
    @topic = Topic.new(params[:topic])

    respond_to do |format|
      if @topic.save
        format.html { redirect_to @topic, notice: 'Topic was successfully created.' }
        format.json { render json: @topic, status: :created, location: @topic }
      else
        format.html { render action: "new" }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end

    #redirect_to @topics, notice: "Topic created successfully"
  end

  # PUT /topics/1
  # PUT /topics/1.json
  def update
    @topic = Topic.find(params[:id])

    respond_to do |format|
      if @topic.update_attributes(params[:topic])
        format.html { redirect_to @topic, notice: 'Topic was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /topics/1
  # DELETE /topics/1.json
  def destroy
    @topic = Topic.find(params[:id])
    @topic.destroy

    respond_to do |format|
      format.html { redirect_to topics_url }
      format.json { head :no_content }
    end
  end

  private

  def find_topic
    @topic = Topic.find(params[:topic_id] || params[:id])
  end

end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/topics/_form.html.erb
<%= form_for(@topic) do |f| %>
  <% if @topic.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@topic.errors.count, "error") %> prohibited this topic from being saved:</h2>

      <ul>
      <% @topic.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/topics/_query.html.erb
<h3><%= @topic.name %></h3>	

<%= render :partial => "/articles/article", :locals => {:searchArticles => @topic.articles} %>

app/views/topics/edit.html.erb
<h1>Editing topic</h1>

<%= render 'form' %>

<%= link_to 'Show', @topic %> |
<%= link_to 'Back', topics_path %>

app/views/topics/index.html.erb
<h1>Topics Management</h1>

<div class="pull-right">
<%= link_to 'New Topic', new_topic_path %>
</div>

<table id="topics" class="table table-bordered table-striped table-hover">
    <thead>
        <tr>
            <th>Order #</th>          
            <th>Topic</th>
            <th>Description</th>
            <th>Article #</th>

            <th></th>
            <th></th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        <% @topics.each do |topic| %>
            <tr>
                <td><%= topic.id %></td>
                <td><%= topic.name %></td>
                <td><%= sanitize(topic.description, :tags=>[])[0..100] %></td>
                <td>0</td>
                <td><%= link_to 'Show', topic %></td>
                <td><%= link_to 'Edit', edit_topic_path(topic) %></td>
                <td><%= link_to 'Delete', topic, method: :delete, data: { confirm: 'Are you sure?' } %></td>                
            </tr>
        <% end %>        

    </tbody>
</table>

<script type="text/javascript">
$('#topics').dataTable({
  "sDom": "<'row'<'span6'l><'span6'f>r>t<'row'<'span6'i><'span6'p>>",
  "sPaginationType": "bootstrap",
        "bPaginate": false,
        "bLengthChange": false,
        "bSort": false,
        "bFilter": false,
        "bAutoWidth": true,
        "oLanguage": {
            "sZeroRecords": "No Article Found",
            "sInfo": "Showing _START_ to _END_ of _TOTAL_ articles",
            "sInfoEmpty": "",
        }          
}); 
</script>

app/views/topics/new.html.erb
<h1>New topic</h1>

<%= render 'form' %>

<%= link_to 'Back', topics_path %>

app/views/topics/query.js.erb
<% if @topic.errors.empty? %>
  $("#content").html("<%= j(render :partial => '/topics/query', :object => @topic) %>");
  highlightActiveTopic(<%= @topic.id%>);
<% else %>
  alert("there was errors with your topic.");
<% end %>

app/views/topics/show.html.erb
<div class="row">
	<%= render :partial => "/layouts/shared/left_panel_topic", :object => @topics, :locals => {:selectTopicId => @topic.id} %>

	<div class="span9" id="content"> 

		<p>
		  <b>Name:</b>
		  <%= @topic.name %>
		</p>

		<p>
		  <b>Description:</b>
		  <%= @topic.description %>
		</p>

		<h3>Articles</h3>	
		<section id="articleSection">
		<%= render :partial => "/articles/article", :locals => {:searchArticles => @topic.articles.all} %>
		</section>
	</div>
</div>